resources:
- repo: self

pool:
  vmImage: windows-latest

pr:
- master
- releases/*

variables:
  BuildConfiguration: 'Debug'
  TeamName: 'Package Experience'

stages:
- stage: Build
  dependsOn: [] 
  jobs:
  - job: build
    steps:
    - template: build/build.yml
      parameters:
        nuspecProperties: 'VersionSuffix=CI-$(Build.BuildNumber)'

- stage: Validate Install
  dependsOn: [] 
  jobs:
  - template: build/validate-install-script.yml

- stage: Validate Install Release
  dependsOn: [] 
  jobs:
  - template: build/validate-install-release-script.yml
