resources:
- repo: self

pool:
  vmImage: windows-latest

trigger:
- master

variables:
  BuildConfiguration: 'Release'
  TeamName: 'Package Experience'

stages:
- stage: Build
  jobs:
  - job: build
    steps:
    - template: build/build.yml
      parameters:
        nuspecProperties: 'VersionSuffix=CI-$(Build.BuildNumber)'

- stage: ValidateInstallScriptWindows
  pool:
    vmImage: windows-latest
  jobs:
  - template: build/validate-install-script-ps.yml
    parameters:
      repo: 'self'

- stage: ValidateInstallScriptLinux
  pool:
    vmImage: ubuntu-latest
  jobs:
  - template: build/validate-install-script-sh.yml
    parameters:
      repo: 'self'  