resources:
- repo: self

pool:
  vmImage: windows-latest

trigger:
- master

variables:
  BuildConfiguration: 'Release'
  TeamName: 'Package Experience'

steps:
- template: build/build.yml
  parameters:
    nuspecProperties: 'VersionSuffix=CI-$(Build.BuildNumber)'
