resources:
- repo: self

pool:
  vmImage: windows-latest

trigger:
- master

variables:
  BuildConfiguration: 'Debug'
  TeamName: 'Package Experience'

stages:
- stage: Build
  jobs:
  - job: build
    steps:
    - template: build/build.yml
      parameters:
        nuspecProperties: 'VersionSuffix=CI-$(Build.BuildNumber)'

- stage: ValidateInstallScript
- template: build/validate-install-script-ps.yml
  parameters:
    pool: 'windows-latest'
    repo: 'self'
- template: build/validate-install-script-sh.yml
  parameters:
    pool: 'ubuntu-latest'
    repo: 'self'  