resources:
- repo: self

queue:
  demands: msbuild

trigger: none

variables:
  BuildConfiguration: 'Release'
  TeamName: 'Package Experience'

steps:
- checkout: self
  clean: true
- task: UniversalPackages@0
  displayName: 'Download public key'
  inputs:
    downloadDirectory: '$(Build.SourcesDirectory)\keys\'
    vstsFeed: '54754426-96db-4f6e-8a3a-64265d1cc147'
    vstsFeedPackage: '015e2771-4069-4e79-9197-263ca7319d09'
    vstsPackageVersion: 1.0.0
- template: build/build.yml
  parameters:
    sign: true
    nuspecProperties: 'Configuration=Release'
