resources:
- repo: self

pool:
  vmImage: windows-latest

trigger:
- master

variables:
  BuildConfiguration: 'Release'
  TeamName: 'Package Experience'

stages:
- stage: Build
  dependsOn: [] 
  jobs:
  - job: build
    steps:
    - template: build/build.yml
      parameters:
        nuspecProperties: 'VersionSuffix=CI-$(Build.BuildNumber)'

- stage: ValidateInstall
  dependsOn: [] 
  jobs:
  - template: build/validate-install-script.yml

- stage: ValidateInstallRelease
  dependsOn: [] 
  jobs:
  - template: build/validate-install-release-script.yml
