//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetCredentialProvider {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuGetCredentialProvider.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find AAD authority from headers, using default: {0}.
        /// </summary>
        internal static string AADAuthorityNotFound {
            get {
                return ResourceManager.GetString("AADAuthorityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found AAD authority override: {0}.
        /// </summary>
        internal static string AADAuthorityOverrideFound {
            get {
                return ResourceManager.GetString("AADAuthorityOverrideFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquired bearer token using &apos;{0}&apos;.
        /// </summary>
        internal static string AcquireBearerTokenSuccess {
            get {
                return ResourceManager.GetString("AcquireBearerTokenSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to acquire session token: {0}.
        /// </summary>
        internal static string AcquireSessionTokenFailed {
            get {
                return ResourceManager.GetString("AcquireSessionTokenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTENTION: User interaction required. 
        ///
        ///    **********************************************************************
        ///
        ///    To sign in, use a web browser to open the page {0} and enter the code {1} to authenticate.
        ///
        ///    **********************************************************************
        ///.
        /// </summary>
        internal static string AdalDeviceFlowMessage {
            get {
                return ResourceManager.GetString("AdalDeviceFlowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceFlow: {0}.
        /// </summary>
        internal static string AdalDeviceFlowRequestedResource {
            get {
                return ResourceManager.GetString("AdalDeviceFlowRequestedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADAL FileCache disabled by environment variable, using the DefaultShared TokenCache.
        /// </summary>
        internal static string AdalFileCacheDisabled {
            get {
                return ResourceManager.GetString("AdalFileCacheDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADAL FileCache location: {0}.
        /// </summary>
        internal static string AdalFileCacheLocation {
            get {
                return ResourceManager.GetString("AdalFileCacheLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using AAD authority: {0}.
        /// </summary>
        internal static string AdalUsingAuthority {
            get {
                return ResourceManager.GetString("AdalUsingAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to acquire bearer token using provider &apos;{0}&apos;.
        /// </summary>
        internal static string AttemptingToAcquireBearerTokenUsingProvider {
            get {
                return ResourceManager.GetString("AttemptingToAcquireBearerTokenUsingProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearer token provider &apos;{0}&apos; failed with exception:\n{1}.
        /// </summary>
        internal static string BearerTokenProviderException {
            get {
                return ResourceManager.GetString("BearerTokenProviderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearer token provider &apos;{0}&apos; didn&apos;t acquire a token.
        /// </summary>
        internal static string BearerTokenProviderReturnedNull {
            get {
                return ResourceManager.GetString("BearerTokenProviderReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This credential provider must not run if any build task environment variables are set. Variables: VSS_NUGET_URI_PREFIXES, VSS_NUGET_ACCESSTOKEN, VSS_NUGET_EXTERNAL_FEED_ENDPOINTS.
        /// </summary>
        internal static string BuildTaskCredProviderIsUsedError {
            get {
                return ResourceManager.GetString("BuildTaskCredProviderIsUsedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This credential provider must be run under the Team Build tasks for NuGet with external endpoint credentials. Appropriate environment variable needs to be set..
        /// </summary>
        internal static string BuildTaskEndpointEnvVarError {
            get {
                return ResourceManager.GetString("BuildTaskEndpointEnvVarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found credentials for endpoint {0}.
        /// </summary>
        internal static string BuildTaskEndpointMatchingUrlFound {
            get {
                return ResourceManager.GetString("BuildTaskEndpointMatchingUrlFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment variable VSS_NUGET_EXTERNAL_FEED_ENDPOINTS did not have credentials for endpoint {0}.
        /// </summary>
        internal static string BuildTaskEndpointNoMatchingUrl {
            get {
                return ResourceManager.GetString("BuildTaskEndpointNoMatchingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This credential provider must be run under the Team Build tasks for NuGet. Appropriate environment variables must be set..
        /// </summary>
        internal static string BuildTaskEnvVarError {
            get {
                return ResourceManager.GetString("BuildTaskEnvVarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to authenticate to {0} from your project collection.
        /// </summary>
        internal static string BuildTaskFailedToAuthenticate {
            get {
                return ResourceManager.GetString("BuildTaskFailedToAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched prefix: {0}.
        /// </summary>
        internal static string BuildTaskMatchedPrefix {
            get {
                return ResourceManager.GetString("BuildTaskMatchedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string BuildTaskNoMatchingPrefixes {
            get {
                return ResourceManager.GetString("BuildTaskNoMatchingPrefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This provider only handles URIs from the build&apos;s Team Project Collection.
        /// </summary>
        internal static string BuildTaskNoPrefixMatch {
            get {
                return ResourceManager.GetString("BuildTaskNoPrefixMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI Prefixes:.
        /// </summary>
        internal static string BuildTaskUriPrefixes {
            get {
                return ResourceManager.GetString("BuildTaskUriPrefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find cached SessionToken for {0}.
        /// </summary>
        internal static string CachedSessionTokenNotFound {
            get {
                return ResourceManager.GetString("CachedSessionTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception happened when trying to get cached token. Invalidating cache. Message: {0}.
        /// </summary>
        internal static string CacheException {
            get {
                return ResourceManager.GetString("CacheException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caching SessionToken for {0}.
        /// </summary>
        internal static string CachingSessionToken {
            get {
                return ResourceManager.GetString("CachingSessionToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling credential provider.
        /// </summary>
        internal static string CancelMessage {
            get {
                return ResourceManager.GetString("CancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command-line v{0}: {1}.
        /// </summary>
        internal static string CommandLineArgs {
            get {
                return ResourceManager.GetString("CommandLineArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse AAD authority override: {0}.
        /// </summary>
        internal static string CouldNotParseAADAuthorityOverride {
            get {
                return ResourceManager.GetString("CouldNotParseAADAuthorityOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse Device Flow Timeout override: {0}.
        /// </summary>
        internal static string CouldNotParseDeviceFlowTimeoutOverride {
            get {
                return ResourceManager.GetString("CouldNotParseDeviceFlowTimeoutOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse Session Time override: {0}.
        /// </summary>
        internal static string CouldNotParseSessionTimeOverride {
            get {
                return ResourceManager.GetString("CouldNotParseSessionTimeOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPS CreateSessionToken Activity ID: {0}.
        /// </summary>
        internal static string CreateSessionTokenActivityId {
            get {
                return ResourceManager.GetString("CreateSessionTokenActivityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a progress reporter with interval: {0}.
        /// </summary>
        internal static string CreatingProgressReporter {
            get {
                return ResourceManager.GetString("CreatingProgressReporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse credentials.
        /// </summary>
        internal static string CredentialParseFailure {
            get {
                return ResourceManager.GetString("CredentialParseFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials not found..
        /// </summary>
        internal static string CredentialsNotFound {
            get {
                return ResourceManager.GetString("CredentialsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device flow authentication failed. User was presented with device flow, but didn&apos;t react within {0} seconds..
        /// </summary>
        internal static string DeviceFlowTimedOut {
            get {
                return ResourceManager.GetString("DeviceFlowTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPAPI not available on non-Windows platforms, using the DefaultShared TokenCache.
        /// </summary>
        internal static string DPAPIUnavailableNonWindows {
            get {
                return ResourceManager.GetString("DPAPIUnavailableNonWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking credentials for endpoint: {0}.
        /// </summary>
        internal static string EndpointCredentialCheck {
            get {
                return ResourceManager.GetString("EndpointCredentialCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse endpoint.
        /// </summary>
        internal static string EndpointParseFailure {
            get {
                return ResourceManager.GetString("EndpointParseFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Environment Variables
        ///    The following is a list of environment variables that can be used to modify the
        ///    behavior of the credential provider. They may be used for workarounds but their
        ///    use is not supported. Use at your own risk.
        ///
        ///Log Path
        ///    {0}
        ///        Absolute path to a log file where the provider will write log messages.
        ///
        ///Session Token Cache Enabled
        ///    {1}
        ///        Boolean to enable/disable the Session Token cache.
        ///
        ///ADAL Authority
        ///    {2}
        ///        Set to override the authority used when  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnvironmentVariableHelp {
            get {
                return ResourceManager.GetString("EnvironmentVariableHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to exchange the bearer token for an Azure DevOps session token..
        /// </summary>
        internal static string ExchangingBearerTokenForSessionToken {
            get {
                return ResourceManager.GetString("ExchangingBearerTokenForSessionToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faulted on message: {0}.
        /// </summary>
        internal static string FaultedOnMessage {
            get {
                return ResourceManager.GetString("FaultedOnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found AAD Authority from 401 headers: {0}.
        /// </summary>
        internal static string FoundAADAuthorityFromHeaders {
            get {
                return ResourceManager.GetString("FoundAADAuthorityFromHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found cached SessionToken for {0}.
        /// </summary>
        internal static string FoundCachedSessionToken {
            get {
                return ResourceManager.GetString("FoundCachedSessionToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found hosts in environment to add to {0}.
        /// </summary>
        internal static string FoundHostsInEnvironment {
            get {
                return ResourceManager.GetString("FoundHostsInEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling auth request, Uri: {0}, IsRetry: {1}, IsNonInteractive: {2}, CanShowDialog: {3}.
        /// </summary>
        internal static string HandlingAuthRequest {
            get {
                return ResourceManager.GetString("HandlingAuthRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling &apos;{0}&apos; &apos;{1}&apos;. Time elapsed in ms: {2} - Payload: {3}.
        /// </summary>
        internal static string HandlingRequest {
            get {
                return ResourceManager.GetString("HandlingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalidating SessionToken cache for {0}.
        /// </summary>
        internal static string InvalidatingCachedSessionToken {
            get {
                return ResourceManager.GetString("InvalidatingCachedSessionToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsRetry: {0}.
        /// </summary>
        internal static string IsRetry {
            get {
                return ResourceManager.GetString("IsRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log starts at {0}.
        /// </summary>
        internal static string LogStartsAt {
            get {
                return ResourceManager.GetString("LogStartsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No provided endpoint matched the given uri.
        /// </summary>
        internal static string NoEndpointMatch {
            get {
                return ResourceManager.GetString("NoEndpointMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No feed endpoints found.
        /// </summary>
        internal static string NoEndpointsFound {
            get {
                return ResourceManager.GetString("NoEndpointsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not running bearer token provider &apos;{0}&apos;.
        /// </summary>
        internal static string NotRunningBearerTokenProvider {
            get {
                return ResourceManager.GetString("NotRunningBearerTokenProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing json.
        /// </summary>
        internal static string ParsingJson {
            get {
                return ResourceManager.GetString("ParsingJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out waiting for plug-in operations to complete.
        /// </summary>
        internal static string PluginTimedOut {
            get {
                return ResourceManager.GetString("PluginTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [REDACTED].
        /// </summary>
        internal static string Redacted {
            get {
                return ResourceManager.GetString("Redacted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring a cancellation exception during request handling. Exception: {0}, Message: {1}.
        /// </summary>
        internal static string RequestHandlerCancelingExceptionMessage {
            get {
                return ResourceManager.GetString("RequestHandlerCancelingExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request uri cannot be null.
        /// </summary>
        internal static string RequestUriNull {
            get {
                return ResourceManager.GetString("RequestUriNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caught exception processing {0}  (RequestId: {1}).
        /// </summary>
        internal static string ResponseHandlerException {
            get {
                return ResourceManager.GetString("ResponseHandlerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running in plug-in mode.
        /// </summary>
        internal static string RunningInPlugin {
            get {
                return ResourceManager.GetString("RunningInPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running in stand-alone mode.
        /// </summary>
        internal static string RunningInStandAlone {
            get {
                return ResourceManager.GetString("RunningInStandAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending response: &apos;{0}&apos; &apos;{1}&apos;. Time elapsed in ms: {2}.
        /// </summary>
        internal static string SendingResponse {
            get {
                return ResourceManager.GetString("SendingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionToken cache disabled by environment.
        /// </summary>
        internal static string SessionTokenCacheDisabled {
            get {
                return ResourceManager.GetString("SessionTokenCacheDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionToken cache location: {0}.
        /// </summary>
        internal static string SessionTokenCacheLocation {
            get {
                return ResourceManager.GetString("SessionTokenCacheLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to gain a lock on the credential cache..
        /// </summary>
        internal static string SessionTokenCacheMutexFail {
            get {
                return ResourceManager.GetString("SessionTokenCacheMutexFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of CredentialProvider is accessing the credential cache, waiting for it to become available..
        /// </summary>
        internal static string SessionTokenCacheMutexMiss {
            get {
                return ResourceManager.GetString("SessionTokenCacheMutexMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential provider shutting down..
        /// </summary>
        internal static string ShuttingDown {
            get {
                return ResourceManager.GetString("ShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping {0}, cannot provide credentials for {1}.
        /// </summary>
        internal static string SkippingCredentialProvider {
            get {
                return ResourceManager.GetString("SkippingCredentialProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception when fetching the authorization endpoint: {0}.
        /// </summary>
        internal static string SPSAuthEndpointException {
            get {
                return ResourceManager.GetString("SPSAuthEndpointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find SPS authorization endpoint for {0}.
        /// </summary>
        internal static string SPSAuthEndpointNotFound {
            get {
                return ResourceManager.GetString("SPSAuthEndpointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting stopwatch for {1} {2}.
        /// </summary>
        internal static string StartRequestHandlerStopwatch {
            get {
                return ResourceManager.GetString("StartRequestHandlerStopwatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time elapsed in milliseconds after sending response &apos;{0}&apos; &apos;{1}&apos;: {2}.
        /// </summary>
        internal static string TimeElapsedAfterSendingResponse {
            get {
                return ResourceManager.GetString("TimeElapsedAfterSendingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI: {0}.
        /// </summary>
        internal static string Uri {
            get {
                return ResourceManager.GetString("Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happened while parsing json: {0}.
        /// </summary>
        internal static string VstsBuildTaskExternalCredentialCredentialProviderError {
            get {
                return ResourceManager.GetString("VstsBuildTaskExternalCredentialCredentialProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception trying to generate Azure DevOps token: {0}, message: {1}, stack: {2}.
        /// </summary>
        internal static string VSTSCreateSessionException {
            get {
                return ResourceManager.GetString("VSTSCreateSessionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not obtain credentials for {0}.
        /// </summary>
        internal static string VSTSCredentialsNotFound {
            get {
                return ResourceManager.GetString("VSTSCredentialsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found SessionToken for {0}.
        /// </summary>
        internal static string VSTSSessionTokenCreated {
            get {
                return ResourceManager.GetString("VSTSSessionTokenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting a {0} token valid for duration {1}, valid until {2} UTC. Note that the generated token may have different validity than requested..
        /// </summary>
        internal static string VSTSSessionTokenValidity {
            get {
                return ResourceManager.GetString("VSTSSessionTokenValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While the plugin was shutting down:.
        /// </summary>
        internal static string WhileShuttingDown {
            get {
                return ResourceManager.GetString("WhileShuttingDown", resourceCulture);
            }
        }
    }
}
