# This sample is for Artifacts Credential Provider version 0.1.28 and it is incompatible with greater versions due to the .NET Core version this sample uses.

# downloading the dotnet sdk image. Could be any docker sdk image with sdk > 9.0.2 
# With nuget plugin dotnet tool install support https://learn.microsoft.com/nuget/release-notes/nuget-6.13#summary-whats-new-in-6130)
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS dotnet-builder
ARG FEED_URL
ARG PAT

# Add dotnet tools to path
ENV PATH="$PATH:/root/.dotnet/tools"

# download and install latest credential provider.
# use --version X.* to pin to a specific major version.
RUN dotnet tool install --global  Microsoft.Artifacts.CredentialProvider.NuGet.Tool --source https://api.nuget.org/v3/index.json

# Optional
WORKDIR /workdir
COPY ./ .

# Optional: Sometimes the http client hangs because of a .NET issue. Setting this in dockerfile helps 
ENV DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0

# Environment variable to enable session token cache. More on this here: https://github.com/Microsoft/artifacts-credprovider#help
ENV ARTIFACTS_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED true

# Environment variable for adding endpoint credentials. More on this here: https://github.com/Microsoft/artifacts-credprovider#help
# Add "FEED_URL" AND "PAT" using --build-arg in docker build step. "endpointCredentials" field is an array, you can add multiple endpoint configurations.
# Make sure that you *do not* hard code the "PAT" here. That is a sensitive information and must not be checked in.
ENV ARTIFACTS_CREDENTIALPROVIDER_EXTERNAL_FEED_ENDPOINTS {\"endpointCredentials\": [{\"endpoint\":\"${FEED_URL}\", \"username\":\"ArtifactsDocker\", \"password\":\"${PAT}\"}]}

# Use this if you have a nuget.config file with all the endpoints.
RUN dotnet restore

# Optional: Extended step to build the app using dotnet msbuild. 
RUN dotnet build dirs.proj
